apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: osba-namespace-tagging-webhook
webhooks:
- name: osba-namespace-tagging-webhook.lab.pathfinder.gov.bc.ca
  clientConfig:
    service:
      namespace: provisioning-tools
      name: admission-control
      path: "/tag"
    rules:
    - operations:
      - CREATE
      apiGroups:
      - ""
      apiVersions:
      - "*"
      resources:
      - ServiceInstance
    failurePolicy: Fail