---
- name: Create a volume claim and attach to pod
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    PVC_STORAGE_CLASS: gluster-cns-block
    PVC_TEMPLATE_NAME: mytest
    PVC_TEMPLATE_LABEL: mytest
    PVC_VOLUME_CLAIM_NAME: mytest
    PVC_ACCCESS_MODE: mytest
    PVC_VOLUME_SIZE: 1
    PVC_VOLUME_NAME: mytest
  pre_tasks:
  - fail:
      msg: "This playbook requires {{item}} to be set."
    when: item is not defined or item == ''
    with_items:
    - PVC_TEMPLATE_NAME
    - PVC_TEMPLATE_LABEL
    - PVC_VOLUME_CLAIM_NAME
    - PVC_ACCCESS_MODE
    - PVC_VOLUME_SIZE
    - PVC_VOLUME_NAME
    - PVC_STORAGE_CLASS
  tasks:
    - name: gather deploy config info
      shell: oc get dc | awk  'NR >1 {print $1}'
      register: dc_apps_listing
    - name: gather pvc info
      shell: "oc volume dc --all {{ item }}|tr -d '\n'|sed 's/[()]//g'>/tmp/{{item}}_pvc_info.txt"
      shell: "oc volume dc --all {{ item }}|tr -d '\n'|sed 's/[()]//g'|awk '{print $1}'"
      register: dc_config_name
      shell: "oc volume dc --all {{ item }}|tr -d '\n'|sed 's/[()]//g'|awk '{print $2}'"
      register: dc_config_name
      with_items: "{{dc_apps_listing.stdout_lines}}"
