apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: glusterfs-cluster-app
spec:
  ports:
  - port: 1
    protocol: TCP
    targetPort: 1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
