#!/usr/bin/env bash
NOOP=
timestamp() { date +"%Y-%m-%d %H:%M:%S %Z"; }
echo "$(timestamp): Delete old logs"
find /logs -type f -mtime 180 -delete
rc=$?
if [ $rc -ne 0 ] ; then
  echo "$(timestamp): Log prune failed"
  exit $rc
fi
echo "$(timestamp): Completed"

