---
apiVersion: v1
kind: List
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "job-runner"
    namespace: "advsol-ops"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "job-runner"
    namespace: "advsol-ops"
  spec:
    failedBuildsHistoryLimit: 1
    successfulBuildsHistoryLimit: 2
    runPolicy: Serial
    source:
      type: Git
      git:
        ref: "cron-image"
        uri: "https://github.com/BCDevOps/openshift-tools.git"
      contextDir: "monitoring/openshift/cronjobs"
#      sourceSecret:
#        name: "${GIT_KEY}"
    strategy:
      dockerStrategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "job-runner:latest"
