---
    - name: Create user
      uri:
        url: "{{ objstore_admin_url }}/object/users.json"
        method: POST
        validate_certs: no
        headers:
          Cookie: "{{ admin_login.set_cookie }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ lookup('template','cr-obj-user.json.j2') }}"
      register: cruser
      ignore_errors: true
    
    - name: show user creation results
      debug:
        msg: "{{ cruser }}"

    - name: get token list for user
      uri:
        url: "{{ objstore_admin_url }}/object/user-secret-keys/{{ objectserviceaccount.name }}.json"
        method: GET
        return_content: yes
        validate_certs: no
        headers:
          Cookie: "{{ admin_login.set_cookie }}"
      register: exToken
      ignore_errors: true

    - name: Create token for user
      uri:
        url: "{{ objstore_admin_url }}/object/user-secret-keys/{{ objectserviceaccount.name }}.json"
        method: POST
        validate_certs: no
        headers:
          Cookie: "{{ admin_login.set_cookie }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ lookup('template','cr-user-token.json.j2') }}"
      register: crtoken
      ignore_errors: true
      # changed_when: 
      #   - crtoken.json.link.href
      #   - crtoken.status == 200
    
    - name: Set Owner Token
      set_fact:
        s3_access_key_id: "{{ objectserviceaccount.name }}"
        s3_access_key_secret: "{{ crtoken.json.secret_key }}"
