---
- name: Node Service Restart
  hosts: all
  serial: 1
  tasks:
    - name: Cordon {{ inventory_hostname | lower }}
      command: >
        oc adm cordon {{ inventory_hostname | lower }}
      delegate_to: localhost
      register: l_drain_result
      until: not l_drain_result | failed
      retries: 60
      delay: 60

    - name: Restart Node service
      systemd:
        name: atomic-openshift-node.service
        state: restarted

    - name: Let node status settle
      wait_for:
        timeout: 5

    - name: Wait for {{ inventory_hostname }} to be ready
      shell: oc get nodes {{ inventory_hostname }} | awk 'NR>1 {print $2}'
      register: result
      until: result.stdout == "Ready,SchedulingDisabled"
      retries: 40
      delay: 15
      delegate_to: localhost

    - name: Set {{ inventory_hostname | lower }} schedulability
      command: >
        oc adm uncordon {{ inventory_hostname | lower }}
      delegate_to: localhost
      delay: 60

