---
- name: OCP Monitoring
  hosts: all
  tasks:
    - name: Logrotate
      copy:
        src: files/logrotate.conf
        dest: /etc/logrotate.d/ocp-monitor
    - name: OCP Script
      template:
        src: templates/ocp-monitor.j2
        dest: /usr/local/bin/ocp-monitor
        mode: 0700
    - name: Metrics script
      copy:
        src: files/metrics-health-check
        dest: /usr/local/bin/metrics-health-check
        mode: 0700
      when: ansible_fqdn == "ociopf-d-100.dmz"
    - name: OCP Monitor Ccron
      cron:
        name: OCP Monitor
        cron_file: /etc/cron.d/ocp-monitor
        user: root
        minute: "*/5"
        job: /usr/local/bin/ocp-monitor 2>&1 >> /var/log/ocp-monitor.log

