---
- name: Load Variables
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check for cluster var
      fail:
        msg: "Please define cluster on the command line with --extra-vars cluster=<cluster> , to load the correct variable file"
      when: "cluster is undefined"

- name: OCP Monitoring
  hosts: all
  vars_files:
    - "vars/{{ cluster }}.yaml"
    - "vault/{{ cluster }}.yaml"
  tasks:
    - name: Check for required variables
      fail:
        msg: "Please define {{ item }}"
      when: item is undefined
      run_once: True
      with_items:
      - primary_master
      - api_url
      - router_dc
      - registry_service
      - canary_route
      - metrics_url
      - sa_token

    - name: Logrotate
      copy:
        src: files/logrotate.conf
        dest: /etc/logrotate.d/ocp-monitor

    - name: OCP Script
      template:
        src: templates/ocp-monitor.j2
        dest: /usr/local/bin/ocp-monitor
        mode: 0700

    - name: Metrics script
      copy:
        src: files/metrics-health-check
        dest: /usr/local/bin/metrics-health-check
        mode: 0700
      when: ansible_fqdn == primary_master

    - name: OCP Monitor Config Dir
      file:
        path: /etc/ocp-monitor
        mode: 0700
        state: directory
      when: ansible_fqdn == primary_master

    - name: OCP Monitor - SA token
      copy:
        dest: /etc/ocp-monitor/esit-monitor-sa-token
        content: "{{ sa_token }}"
        mode: 0700
      when: ansible_fqdn == primary_master

    - name: Cert Monitor script
      template:
        src: templates/cert-monitor.j2
        dest: /usr/local/bin/cert-monitor
        mode: 0700
      when: ansible_fqdn == primary_master

    - name: OCP Monitor Ccron
      cron:
        name: OCP Monitor
        cron_file: /etc/cron.d/ocp-monitor
        user: root
        minute: "*/5"
        hour: '{{ cron_hour | default(omit) }}'
        weekday: '{{ cron_weekday | default(omit) }}'
        job: /usr/local/bin/ocp-monitor >> /var/log/ocp-monitor.log 2>&1

    - name: Cert Monitor Ccron
      cron:
        name: Cert Monitor
        cron_file: /etc/cron.d/ocp-cert-monitor
        user: root
        minute: "0"
        hour: "9"
        weekday: '{{ cron_weekday | default(omit) }}'
        job: /usr/local/bin/cert-monitor >/dev/null 2>&1
      when: ansible_fqdn == primary_master
