---
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: egress-internet
spec:
  description: |
    allow the ocp101 namespace to talk to the internet.
  source:
    - - $namespace=devops-platform-security-demo
  destination:
    - - ext:network=any
---
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: intra-namespace-comms
spec:
  description: |
    allow the devops-platform-security-demo namespace to talk to itself
  source:
    - - $namespace=devops-platform-security-demo
  destination:
    - - $namespace=devops-platform-security-demo
---
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: intra-namespace-comms
spec:
  description: |
    allow devops-platform-security-demo pods to talk to the k8s api
  destination:
  - - int:network=internal-cluster-api-endpoint
  source:
  - - $namespace=devops-platform-security-demo
parameter:
- description: Namespace
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: ''