---
- name: cordon
  include_tasks: cordon.yml
  when: inventory_hostname not in groups['masters']
- name: yum update
  include_tasks: yum_update.yml
  when: yum_update == "yes"
- name: reboot server
  include_tasks: reboot.yml
- name: uncordon
  include_tasks: uncordon.yml
  when: inventory_hostname not in groups['masters']
