---
- name: Update docker options file
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^OPTIONS=.*$'
    line: "OPTIONS=' --selinux-enabled --log-driver=json-file --log-opt max-size=50m --log-opt max-file=5 --signature-verification=False'"
  notify:
  - Restart docker

- name: Restart docker
  systemd:
    name: docker.service
    state: restarted
    daemon_reload: yes
  register: r_docker_restart_docker_result
  until: not (r_docker_restart_docker_result is failed)
  retries: 3
  delay: 30

