---
- name: Wait for {{ inventory_hostname }} to be ready
  shell: oc get nodes {{ inventory_hostname }} | awk 'NR>1 {print $2}'
  register: result
  until: result.stdout == "Ready,SchedulingDisabled"
  retries: 40
  delay: 15
  delegate_to: localhost

- name: Set {{ inventory_hostname | lower }} schedulability
  command: >
    oc adm uncordon {{ inventory_hostname | lower }}
  delegate_to: localhost
  delay: 60

- name: Wait for {{ inventory_hostname | lower }} to have a running router
  shell: oc get pods -n default -o wide | grep {{ inventory_hostname | lower }} | grep ^router | awk '{print $2}'
  register: result
  until: result.stdout.find("2/2") != -1
  retries: 25
  delay: 15
  delegate_to: localhost
  when: inventory_hostname in groups['infra']

